id: 'ttihp0p4'
name: 'Tiny Tapeout IHP 0p4 (CMOS5L)'
pdk: 'ihp-sg13cmos5l'
end_date: '2026-04-01'
project_dir: 'projects'
top_level_macro: 'tt_ihp_wrapper'
powered_netlists: false
no_power_gating: true

datasheet_config:
  theme_override_colour: tt.colours.THEME_SKY_BLUE
  link_override_colour: tt.colours.THEME_SKY_BLUE

  # include:
    # - docs/chip_map.typ
    # - docs/funding.typ
